### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by Stephan-Pauld** [SkullTech/reddit-auto-poster.py#2]
DeprecationWarning: Reddit will check for validation on all posts around May-June 2020. It is recommended to check for validation by setting reddit.validate_on_submit to True.

I found a post about reddit.validate_on_submit = True after initializing your Reddit instance. 
where would I place this line to fix this issue.. Not super python savvy I appreciate the script and want to use it!

**Comment by skulltech** [comment]
Thanks for pointing it out! Well, I looked it up and seems like it just they're enforcing some post validation rules. As long as your posts in `posts.json` are okay according to the subreddit rules, you should be good.

If you just want the warning to go away, just put this line in the intialization method of the `Golem` class, just after the `praw.Reddit` class is generated.

```python
self.reddit.validate_on_submit = True
```

So, after making the change, the relevant part of the `Golem` class should look like this
```python
class Golem:
    def __init__(self, config):
        self.reddit = praw.Reddit(client_id=config['CONFIG']['CLIENT_ID'], 
                                  client_secret=config['CONFIG']['CLIENT_SECRET'],
                                  username=config['CONFIG']['USERNAME'],
                                  password=config['CONFIG']['PASSWORD'],
                                  user_agent='Script by u/SkullTech101')
        self.reddit.validate_on_submit = True
```

Do you want to make a pull request making this change? If you want then I'll let you go ahead and do that, seems like it'll be your first pull-request!! Could be your first step to open-source contribution. Otherwise I can just make this change myself. Your choice.

**Comment by Stephan-Pauld** [comment]
Thanks so much for this reply!! I actually did get it working the error just pops up but now I can get rid of the error!!

I do have another question ill just ask is here since its not an "issue" when creating a reddit post sometime you have options "post , image&video, link , Poll" is there a way I could have it select link then enter a URL?

**Comment by skulltech** [comment]
Well that feature is already there. You'll just have to specify the `URL` parameter in the `posts.json` file. For example, if your `posts.json` looks like the following

```json
{
    "Posts": [
        {
            "Subreddits": ["test", "sandbox"],
            "Title": "Test post by reddit-auto-poster.py",
            "URL": "https://github.com/SkullTech/reddit-auto-poster.py"
        },
        {
            "Subreddits": ["SkullTest"],
            "Title": "Test post by reddit-auto-poster.py",
            "Text": "Testing. Don't mind me."
        }
    ]
}
```

The it will post the _link_ https://github.com/SkullTech/reddit-auto-poster.py to the `test` and `sandbox` subreddits, because I put the link in the `URL` parameter. And if you want to post a text post, then use the `Text` parameter. 

Let me know if that makes sense.

**Comment by Stephan-Pauld** [comment]
This does make sense and this is currently how I have been using this however when use the url its creating it in the text field on reddit in the "post" tab rather than the "link" tab.

For instance if I create a post on reddit under the "post" tab type my title and creat a url in the "text" field my post will be created and place on the subreddit. However there will be no thumbnail when people are looking on the subreddit.

BUT if I am on a subreddit that allows the "link" tab and I enter my title and place in a "link" and the post is now created there will be a thumbnail on the subreddit for people to view. 

I am posting on a lot of of image subreddits and my posts are getting lost as my post is much smaller and doesnt have a thumbnail.

I hope this makes sense!  I by no means expect you to add this just curious if it could even be done! Ive been teaching myself python and this is much much over my head xD but its fun to read your code and learn from it!

**Comment by skulltech** [comment]
@Stefler12 I see, so you want the _preview_ thing, with the thumbnails and everything. I'll look into that. I'll keep posted on any progress.

**Comment by Stephan-Pauld** [comment]
When scrolling through a subreddit [Preview of image or video](https://gyazo.com/78a27250617585ba8c39b4d49b877eae) This is when posted under the link tab you can see there would be a preview on the right side of the post in the subreddit

here is what i mean [link tab](https://gyazo.com/9ec2c5cbc3783ac87db1dc71c7699847)

and here is what it looks like when you post to a subreddit with the [post tab](https://gyazo.com/5e331c966dc97c5b8f911e43e68ea5b3) it just shows the hyper text.

here is the posting process of the [post tab](https://gyazo.com/394124ee41796f2fe6bc98bfea07bc1b)

If this makes sense :) Hope you are well!

**Comment by skulltech** [comment]
Well, I looked at it and I think you misunderstood, you're not using the script correctly. I'll explain with some clear examples this time.

Try with the following `posts.json`
```json
{
    "Posts": [
        {
            "Subreddits": ["test"],
            "Title": "Test post by reddit-auto-poster.py",
            "URL": "https://i.imgur.com/henzLlh.jpg"
        }
    ]
}
```

This produces [this post](https://imgur.com/aaTKpcx).

Another example, this time with a normal link, not an image. Following is the `posts.json`
```json
{
    "Posts": [
        {
            "Subreddits": ["test"],
            "Title": "Test post by reddit-auto-poster.py",
            "URL": "https://sumit-ghosh.com/articles/serverless-url-shortner-lambda-s3-cloudfront/"
        }
    ]
}
```
And this creates [this post](https://imgur.com/iWbnUfk).

So you can see, the script does what you're trying to do. I think you're using the `Text` attribute in the `posts.json` file, that's why your posts are getting posted as text post.

If you're still unclear, give me the `posts.json` file you're using and I'll take a look at what's going wrong.

**Comment by skulltech** [comment]
@Stefler12 Closing this for now. If you still have some questions, feel free to comment and I'll open it again.
